# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/terry/Work/ODEA/qAlgorithms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/terry/Work/ODEA/qAlgorithms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/terry/Work/ODEA/qAlgorithms/CMakeFiles /home/terry/Work/ODEA/qAlgorithms//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/terry/Work/ODEA/qAlgorithms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qAlgorithms

# Build rule for target.
qAlgorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qAlgorithms
.PHONY : qAlgorithms

# fast build rule for target.
qAlgorithms/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/build
.PHONY : qAlgorithms/fast

external/CDFlib/cdflib.o: external/CDFlib/cdflib.cpp.o
.PHONY : external/CDFlib/cdflib.o

# target to build an object file
external/CDFlib/cdflib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/external/CDFlib/cdflib.cpp.o
.PHONY : external/CDFlib/cdflib.cpp.o

external/CDFlib/cdflib.i: external/CDFlib/cdflib.cpp.i
.PHONY : external/CDFlib/cdflib.i

# target to preprocess a source file
external/CDFlib/cdflib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/external/CDFlib/cdflib.cpp.i
.PHONY : external/CDFlib/cdflib.cpp.i

external/CDFlib/cdflib.s: external/CDFlib/cdflib.cpp.s
.PHONY : external/CDFlib/cdflib.s

# target to generate assembly for a file
external/CDFlib/cdflib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/external/CDFlib/cdflib.cpp.s
.PHONY : external/CDFlib/cdflib.cpp.s

external/StreamCraft/src/StreamCraft_mzml.o: external/StreamCraft/src/StreamCraft_mzml.cpp.o
.PHONY : external/StreamCraft/src/StreamCraft_mzml.o

# target to build an object file
external/StreamCraft/src/StreamCraft_mzml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/external/StreamCraft/src/StreamCraft_mzml.cpp.o
.PHONY : external/StreamCraft/src/StreamCraft_mzml.cpp.o

external/StreamCraft/src/StreamCraft_mzml.i: external/StreamCraft/src/StreamCraft_mzml.cpp.i
.PHONY : external/StreamCraft/src/StreamCraft_mzml.i

# target to preprocess a source file
external/StreamCraft/src/StreamCraft_mzml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/external/StreamCraft/src/StreamCraft_mzml.cpp.i
.PHONY : external/StreamCraft/src/StreamCraft_mzml.cpp.i

external/StreamCraft/src/StreamCraft_mzml.s: external/StreamCraft/src/StreamCraft_mzml.cpp.s
.PHONY : external/StreamCraft/src/StreamCraft_mzml.s

# target to generate assembly for a file
external/StreamCraft/src/StreamCraft_mzml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/external/StreamCraft/src/StreamCraft_mzml.cpp.s
.PHONY : external/StreamCraft/src/StreamCraft_mzml.cpp.s

src/qalgorithms_input_output.o: src/qalgorithms_input_output.cpp.o
.PHONY : src/qalgorithms_input_output.o

# target to build an object file
src/qalgorithms_input_output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_input_output.cpp.o
.PHONY : src/qalgorithms_input_output.cpp.o

src/qalgorithms_input_output.i: src/qalgorithms_input_output.cpp.i
.PHONY : src/qalgorithms_input_output.i

# target to preprocess a source file
src/qalgorithms_input_output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_input_output.cpp.i
.PHONY : src/qalgorithms_input_output.cpp.i

src/qalgorithms_input_output.s: src/qalgorithms_input_output.cpp.s
.PHONY : src/qalgorithms_input_output.s

# target to generate assembly for a file
src/qalgorithms_input_output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_input_output.cpp.s
.PHONY : src/qalgorithms_input_output.cpp.s

src/qalgorithms_main.o: src/qalgorithms_main.cpp.o
.PHONY : src/qalgorithms_main.o

# target to build an object file
src/qalgorithms_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_main.cpp.o
.PHONY : src/qalgorithms_main.cpp.o

src/qalgorithms_main.i: src/qalgorithms_main.cpp.i
.PHONY : src/qalgorithms_main.i

# target to preprocess a source file
src/qalgorithms_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_main.cpp.i
.PHONY : src/qalgorithms_main.cpp.i

src/qalgorithms_main.s: src/qalgorithms_main.cpp.s
.PHONY : src/qalgorithms_main.s

# target to generate assembly for a file
src/qalgorithms_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_main.cpp.s
.PHONY : src/qalgorithms_main.cpp.s

src/qalgorithms_measurement_data.o: src/qalgorithms_measurement_data.cpp.o
.PHONY : src/qalgorithms_measurement_data.o

# target to build an object file
src/qalgorithms_measurement_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_measurement_data.cpp.o
.PHONY : src/qalgorithms_measurement_data.cpp.o

src/qalgorithms_measurement_data.i: src/qalgorithms_measurement_data.cpp.i
.PHONY : src/qalgorithms_measurement_data.i

# target to preprocess a source file
src/qalgorithms_measurement_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_measurement_data.cpp.i
.PHONY : src/qalgorithms_measurement_data.cpp.i

src/qalgorithms_measurement_data.s: src/qalgorithms_measurement_data.cpp.s
.PHONY : src/qalgorithms_measurement_data.s

# target to generate assembly for a file
src/qalgorithms_measurement_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_measurement_data.cpp.s
.PHONY : src/qalgorithms_measurement_data.cpp.s

src/qalgorithms_qbin.o: src/qalgorithms_qbin.cpp.o
.PHONY : src/qalgorithms_qbin.o

# target to build an object file
src/qalgorithms_qbin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qbin.cpp.o
.PHONY : src/qalgorithms_qbin.cpp.o

src/qalgorithms_qbin.i: src/qalgorithms_qbin.cpp.i
.PHONY : src/qalgorithms_qbin.i

# target to preprocess a source file
src/qalgorithms_qbin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qbin.cpp.i
.PHONY : src/qalgorithms_qbin.cpp.i

src/qalgorithms_qbin.s: src/qalgorithms_qbin.cpp.s
.PHONY : src/qalgorithms_qbin.s

# target to generate assembly for a file
src/qalgorithms_qbin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qbin.cpp.s
.PHONY : src/qalgorithms_qbin.cpp.s

src/qalgorithms_qpattern.o: src/qalgorithms_qpattern.cpp.o
.PHONY : src/qalgorithms_qpattern.o

# target to build an object file
src/qalgorithms_qpattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qpattern.cpp.o
.PHONY : src/qalgorithms_qpattern.cpp.o

src/qalgorithms_qpattern.i: src/qalgorithms_qpattern.cpp.i
.PHONY : src/qalgorithms_qpattern.i

# target to preprocess a source file
src/qalgorithms_qpattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qpattern.cpp.i
.PHONY : src/qalgorithms_qpattern.cpp.i

src/qalgorithms_qpattern.s: src/qalgorithms_qpattern.cpp.s
.PHONY : src/qalgorithms_qpattern.s

# target to generate assembly for a file
src/qalgorithms_qpattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qpattern.cpp.s
.PHONY : src/qalgorithms_qpattern.cpp.s

src/qalgorithms_qpeaks.o: src/qalgorithms_qpeaks.cpp.o
.PHONY : src/qalgorithms_qpeaks.o

# target to build an object file
src/qalgorithms_qpeaks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qpeaks.cpp.o
.PHONY : src/qalgorithms_qpeaks.cpp.o

src/qalgorithms_qpeaks.i: src/qalgorithms_qpeaks.cpp.i
.PHONY : src/qalgorithms_qpeaks.i

# target to preprocess a source file
src/qalgorithms_qpeaks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qpeaks.cpp.i
.PHONY : src/qalgorithms_qpeaks.cpp.i

src/qalgorithms_qpeaks.s: src/qalgorithms_qpeaks.cpp.s
.PHONY : src/qalgorithms_qpeaks.s

# target to generate assembly for a file
src/qalgorithms_qpeaks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_qpeaks.cpp.s
.PHONY : src/qalgorithms_qpeaks.cpp.s

src/qalgorithms_utils.o: src/qalgorithms_utils.cpp.o
.PHONY : src/qalgorithms_utils.o

# target to build an object file
src/qalgorithms_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_utils.cpp.o
.PHONY : src/qalgorithms_utils.cpp.o

src/qalgorithms_utils.i: src/qalgorithms_utils.cpp.i
.PHONY : src/qalgorithms_utils.i

# target to preprocess a source file
src/qalgorithms_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_utils.cpp.i
.PHONY : src/qalgorithms_utils.cpp.i

src/qalgorithms_utils.s: src/qalgorithms_utils.cpp.s
.PHONY : src/qalgorithms_utils.s

# target to generate assembly for a file
src/qalgorithms_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qAlgorithms.dir/build.make CMakeFiles/qAlgorithms.dir/src/qalgorithms_utils.cpp.s
.PHONY : src/qalgorithms_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... qAlgorithms"
	@echo "... external/CDFlib/cdflib.o"
	@echo "... external/CDFlib/cdflib.i"
	@echo "... external/CDFlib/cdflib.s"
	@echo "... external/StreamCraft/src/StreamCraft_mzml.o"
	@echo "... external/StreamCraft/src/StreamCraft_mzml.i"
	@echo "... external/StreamCraft/src/StreamCraft_mzml.s"
	@echo "... src/qalgorithms_input_output.o"
	@echo "... src/qalgorithms_input_output.i"
	@echo "... src/qalgorithms_input_output.s"
	@echo "... src/qalgorithms_main.o"
	@echo "... src/qalgorithms_main.i"
	@echo "... src/qalgorithms_main.s"
	@echo "... src/qalgorithms_measurement_data.o"
	@echo "... src/qalgorithms_measurement_data.i"
	@echo "... src/qalgorithms_measurement_data.s"
	@echo "... src/qalgorithms_qbin.o"
	@echo "... src/qalgorithms_qbin.i"
	@echo "... src/qalgorithms_qbin.s"
	@echo "... src/qalgorithms_qpattern.o"
	@echo "... src/qalgorithms_qpattern.i"
	@echo "... src/qalgorithms_qpattern.s"
	@echo "... src/qalgorithms_qpeaks.o"
	@echo "... src/qalgorithms_qpeaks.i"
	@echo "... src/qalgorithms_qpeaks.s"
	@echo "... src/qalgorithms_utils.o"
	@echo "... src/qalgorithms_utils.i"
	@echo "... src/qalgorithms_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

