#include <algorithm> // remove duplicates from task list
#include <assert.h>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <filesystem> // printing absolute path in case read fails
#include <fstream>    // write peaks to file @todo remove
#include <iostream>
#include <string>
#include <vector>

#include "qalgorithms_datatypes.h"
#include "qalgorithms_input_output.h"
#include "qalgorithms_read_file.h"
#include "qalgorithms_utils.h"

namespace qAlgorithms
{
#pragma region helpstring

    const char helpinfo[] =
        " help information:\n\n"
        "    qAlgorithms is a software project for non-target screening using mass spectrometry. For more information,\n"
        "    visit our github page: https://github.com/odea-project/qAlgorithms. As of now (2026-06-29),\n"
        "    only mzML files are supported. This program accepts the following command-line arguments:\n\n"
        "      -h, -help:  Open this help menu\n"
        "\n    Input settings:\n"
        "      -i,  -input <PATH> [PATH] : Input files or directories in which to recursively search for .mzML\n"
        "                                  files. You can enter any number of targets, as long as no file starts\n"
        "                                  with a \"-\" or contains two dots in a row. It is possible to use\n"
        "                                  the -i flag multiple times within one execution.\n"
        "                                  Note that:\n"
        "                                  1) qAlgorithms is case-sensitive when searching for files recursively.\n"
        "                                     Make sure all your files have the correct extension (.mzML) and are\n"
        "                                     not all lowercase (.mzml).\n"
        "                                  2) duplicate input files are removed by default, even when they have\n"
        "                                     a different name.\n"
        "                                  3) filenames may never start with a \"-\".\n"
        //   "      -tl, -tasklist <PATH>:      pass a list of file paths to the function. A tasklist can also contain directories\n"
        //   "                                  to search recursively and output directories for different blocks of the input files.\n"
        "\n    Single-file output settings:\n"
        "      Note                      : The filename is always the original filename extended by the polarity\n"
        "                                  and the processing step. For example, printing features of the file\n"
        "                                  \"test.mzML\" would produce the output file \"test_pos_features.csv\".\n"
        "      -o,  -output <DIRECTORY>  : Directory into which all output files should be printed.\n"
        "      -pc, -printcentroids      : Print all centroids produced after the first run of qcentroids.\n"
        "      -pc-mzml, -centroid-mzml  : Centroid and output a modification of the input mzML file. This means that\n"
        "                                  additional properties generated by qAlgorithms will not be preserved.\n"
        "      -pb, -printbins:          : If this flag is set, both bin summary information and\n"
        "                                  all binned centroids will be printed to the output location\n"
        "                                  in addition to the final peak table. The file ends in _bins.csv.\n"
        "      -pf, -printfeatures         Print the feature list as csv.\n"
        //   "      -sp, -subprofile:           (@todo) instead of the peaks, print all proflie-mode data points which\n"
        //   "                                  were used to create the final peaks. This does not return any quality\n"
        //   "                                  scores. Only use this option when reading in prodile mode files.\n"
        "      -px, -printfeatcen        : Print all centroids that are a part of the final feature list,\n"
        "                                  including debug data.\n"
        "      -ppf, -printcomponentsF   : Print the component regressions that belong to the generated feature list.\n"
        "                                  The values for beta 0 are printed in order of the retention time of the\n"
        "                                  associated features (check the feature list for this) and separated by\n"
        "                                  a semicolon. The feature list is always printend if this is set.\n"
        "      -ppb, -printcomponentsB   : Print all centroids that are part of components. Similar to -ppf, but\n"
        "                                  considers the range of the newly constructed regression for which centroids\n"
        "                                  are relevant. Also prints the components themselves.\n"
        "      -pa, -printall            : Print all availvable resutlts. You will probably not need to do this.\n"
        "      -prfsc, -profile-section  : Parse a file and print the profile blocks that fit the filter into a file.\n"
        "                                  The filter is specified in the pattern mz-min, mz-max, rt-min, rt-max given\n"
        "                                  in dalton and minutes respectively.\n"
        "\n    Program behaviour:\n"
        "      -time-min                 : Use minutes as the default for all command-line input (default).\n"
        "      -time-sec                 : Use seconds as the default for all command-line input.\n"
        "                                  Note: Whichever is supplied last will be used, -time-sec -time-min is not an\n"
        "                                  error. All times must be given in the same unit, as this is not checked\n"
        "      -s, -silent               : Do not print progress reports to standard out.\n"
        // @todo add an option for printing all process stats without timing and explanations for use with CLI toolchains
        "      -skip-existing            : Do not write to files that already exist, even if an output option is set.\n"
        "      -skip-error               : If processing fails, the program will not exit and instead start processing\n"
        "                                  the next file in the tasklist.\n"
        "      -skipAhead <n>            : Skip the first n entries in the tasklist when starting processing \n"
        "      -fullLoop                 : Override default behaviour and always perform all possible processing steps,\n"
        "                                  even if the results are not printed.\n"
        "      -log                      : This option is not implemented yet.\n"; // @todo

#pragma endregion helpstring

#pragma region "command line arguments"

    // NOLINTBEGIN(concurrency-mt-unsafe)
    UserInputSettings passCliArgs(int argc, char *argv[])
    {
        UserInputSettings args;
        assert(args.inputPaths.empty());
        assert(args.outputPath.empty());

        volatile bool debug = false;
        if (argc == 1 && !debug)
        {
            args = interactiveMode();
        }

        for (int i = 1; i < argc; i++)
        {
            std::string argument = argv[i];
            if ((argument == "-h") || (argument == "-help"))
            {
                printf("\n    %s%s", argv[0], helpinfo);
                exit(0);
            }
            else if ((argument == "-s") || (argument == "-silent"))
            {
                args.silent = true;
            }
            else if ((argument == "-v") || (argument == "-verbose"))
            {
                args.verboseProgress = true;
            }
            else if ((argument == "-i") || (argument == "-input"))
            {
                ++i;
                if (i == argc)
                {
                    fprintf(stderr, "Error: argument -input was set, but no valid file supplied.\n");
                    return args;
                }
                std::string inputString = argv[i];
                if (inputString[0] == '-')
                {
                    fprintf(stderr, "Error: argument -input was set, but no valid file supplied.\n");
                    return args;
                }
                for (; i < argc; i++)
                {
                    inputString = argv[i];
                    if (inputString[0] == '-')
                    {
                        break;
                    }
                    args.inputPaths.push_back(inputString);
                }
                --i;
            }
            else if ((argument == "-tl") || (argument == "-tasklist"))
            {
                fprintf(stderr, "Error: tasklist support is not integrated at the moment.\n");

                args.tasklistSpecified = true;
                ++i;
                const char format_err_tl[] = "Error: argument -tasklist was set, but no valid file supplied.\n";
                if (i == argc)
                {
                    fprintf(stderr, format_err_tl);
                    return args;
                }
                std::string inputString = argv[i];
                if (inputString[0] == '-')
                {
                    fprintf(stderr, format_err_tl);
                    return args;
                }
                /*@todo
                the task file should contain a list of all files the program
                should run over. It should give access to additional settings,
                for example per-group output location and multiple recursion points.
                Lines can be commented out with a "#". empty lines are ignored.
                The file must start with a line containing only "TASKFILE" and
                should accept some standardised user data like name and project.
                Suggested options:
                    ADDDATE: The current date (YYYYMMDD) is added with an underscore
                    to the front of the filename
                */
                args.inputPaths.push_back(inputString);
            }

            else if ((argument == "-o") || (argument == "-output"))
            {
                if (args.outputPath != "")
                {
                    fprintf(stderr, "Error: two output locations specified. For complex "
                                    "output location structures, it is recommended you use the tasklist"
                                    " input (not implemented yet).\n");
                    args.outputPath = "";
                    return args;
                }

                ++i;
                if (i == argc)
                {
                    fprintf(stderr, "Error: no output directory specified.\n");
                    return args;
                }
                args.outputPath = argv[i];
            }
            else if ((argument == "-pc") || (argument == "-printcentroids"))
            {
                args.printCentroidsMZML = true;
            }
            else if ((argument == "-pc-mzml") || (argument == "-centroid-mzml"))
            {
                args.printCentroids = true;
            }
            else if ((argument == "-pb") || (argument == "-printbins"))
            {
                args.printBins = true;
            }
            else if ((argument == "-pf") || (argument == "-printfeatures"))
            {
                args.printFeatures = true;
            }
            else if ((argument == "-sp") || (argument == "-subprofile"))
            {
                args.printSubProfile = true;
            }
            else if ((argument == "-ppf") || (argument == "-printcomponentsF"))
            {
                args.printComponentRegs = true;
                args.printFeatures = true;
            }
            else if ((argument == "-ppb") || (argument == "-printcomponentsB"))
            {
                args.printComponentRegs = true;
                args.printComponentBins = true;
            }
            else if ((argument == "-px") || (argument == "-printfeatcen"))
            {
                args.printFeatCens = true;
            }
            else if ((argument == "-pa") || (argument == "-printall"))
            {
                args.printCentroids = true;
                args.printBins = true;
                args.printFeatures = true;
                args.printSubProfile = true;
                args.printFeatCens = true;
                args.printComponentRegs = true;
                args.printComponentBins = true;
            }
            else if ((argument == "-prfsc") || (argument == "-profile-section"))
            {
                args.printProfileSection = true;
                // we expect exactly four floats to be supplied next. The order is always mz -> rt and lower -> upper
                // @todo error handling for bad input
                assert(i + 4 < argc);
                args.prof_lim_mz_lower = std::stof(argv[i + 1]);
                args.prof_lim_mz_upper = std::stof(argv[i + 2]);
                args.prof_lim_rt_lower = std::stof(argv[i + 3]);
                args.prof_lim_rt_upper = std::stof(argv[i + 4]);
                i += 4;
            }
            else if (argument == "-time-min")
            {
                args.time_seconds = false;
            }
            else if (argument == "-time-sec")
            {
                args.time_seconds = true;
            }
            else if (argument == "-log")
            {
                args.doLogging = true;
            }
            else if (argument == "-skip-error")
            {
                fprintf(stderr, "Warning: processing will ignore defective files.\n");
                args.skipError = true;
            }
            else if (argument == "-skipAhead" || argument == "-skip-ahead")
            {
                ++i;
                if (i == argc)
                {
                    fprintf(stderr, "Error: no value to skip ahead specified.\n");
                    return args;
                }

                char *str = argv[i];
                char **endptr = &str - 1; // the position one ahead of str is always defined and non-null
                int skip = strtol(str, endptr, 10);
                if (*endptr == str)
                {
                    fprintf(stderr, "Error: you cannot skip ahead by \"%s\" entries.\n", argv[i]);
                    return args;
                }
                if (skip < 0)
                {
                    fprintf(stderr, "Error: you cannot skip ahead a negative number of entries.\n");
                }

                args.skipAhead = (size_t)skip;
            }
            else
            {
                fprintf(stderr, "Error: unknown argument \"%s\".\n", argument.c_str());
                exit(1);
            }
        } // end of reading in command line arguments

        // adjust time to seconds if necessary
        if (!args.time_seconds)
        {
            args.prof_lim_rt_lower *= 60;
            args.prof_lim_rt_upper *= 60;
        }
        return args;
    }
    // NOLINTEND(concurrency-mt-unsafe)

    UserInputSettings interactiveMode() // @todo this should be replaced by a better debug interface
    {
        // this function is called if qAlgorithms is executed without arguments
        printf("    ### qAlgorithms interactive terminal interface ###\n"
               "relative paths are not supported in this mode\n"
               "drag the folder or file you want to process into this window and press \"enter\" to continue:\n");
        std::string inputPath;
        while (true)
        {
            std::cin >> inputPath; // @todo replace this
            if (std::filesystem::exists(inputPath))
            {
                break;
            }
            printf("Error: The path does not exist.\n");
        }

        UserInputSettings res = UserInputSettings{
            std::vector<std::string>{inputPath},
            ".",
            0,
            never,
            0,
            0,
            0,
            0,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true};

        return res;
    }

    bool inputsAreSensible(UserInputSettings &args)
    {
        // program exits if an error is found, but only after displaying all warnings
        bool goodInputs = true;

        if (args.inputPaths.empty())
        {
            fprintf(stderr, "Error: no input file supplied. Specify a file or directory using the -i or "
                            "-tl flag. Execute qAlgorithms with the -h flag for more information.\n");
            goodInputs = false;
        }
        if (args.outputPath.empty())
        {
            if (args.printCentroids ||
                args.printFeatures ||
                args.printBins ||
                args.printProfileSection)
            {
                std::string badOptions;
                int prevBad = 0;
                if (args.printProfileSection)
                {
                    // if (prevBad > 0) // uncomment if an earlier return point is introduced
                    // {
                    //     badOptions += ", ";
                    // }
                    prevBad += 1;
                    badOptions += "-profile-section";
                }
                if (args.printCentroids)
                {
                    if (prevBad > 0)
                    {
                        badOptions += ", ";
                    }
                    prevBad += 1;
                    badOptions += "-printcentroids";
                }
                if (args.printCentroidsMZML)
                {
                    if (prevBad > 0)
                    {
                        badOptions += ", ";
                    }
                    prevBad += 1;
                    badOptions += "-centroid-mzml";
                }
                if (args.printBins)
                {
                    if (prevBad > 0)
                    {
                        badOptions += ", ";
                    }
                    prevBad += 1;
                    badOptions += "-printbins";
                }
                if (args.printFeatures)
                {
                    if (prevBad > 0)
                    {
                        badOptions += ", ";
                    }
                    prevBad += 1;
                    badOptions += "-printfeatures";
                }

                if (prevBad > 1)
                {
                    fprintf(stderr, "Error: output flags \"%s\" were set, but no output path supplied.\n",
                            badOptions.c_str());
                }
                else
                {
                    fprintf(stderr, "Error: output flag \"%s\" was set, but no output path supplied.\n",
                            badOptions.c_str());
                }
                goodInputs = false;
            }
            else
            {
                fprintf(stderr, "Warning: no output directory specified. No output files will be written.\n");
            }
        }
        else if (!std::filesystem::exists(args.outputPath))
        {
            fprintf(stderr, "Error: the specified output path \"%s\" does not exist.\n", args.outputPath.c_str());
            goodInputs = false;
        }
        else if (std::filesystem::status(args.outputPath).type() != std::filesystem::file_type::directory)
        {
            fprintf(stderr, "Error: the output location must be a directory.\n");
            goodInputs = false;
        }
        if (args.silent && args.verboseProgress)
        {
            fprintf(stderr, "Warning: -verbose overrides -silent.\n");
            args.silent = false;
        }

        // set termination point here so that the program will only process data when necessary
        // note: since this statement is only evaluated once, it must be set up in the same order
        // as the termination points in the main function. Since these cannot be arbitrary, that
        // is not considered an issue for now.
        if (args.printComponentRegs || args.printComponentBins)
        {
            args.term = TerminateAfter::components;
        }
        else if (args.printFeatures || args.printFeatCens || args.printSubProfile)
        {
            args.term = TerminateAfter::features;
        }
        else if (args.printBins)
        {
            args.term = TerminateAfter::binning;
        }
        else if (args.printCentroids)
        {
            args.term = TerminateAfter::centroids;
        }
        else if (args.printProfileSection)
        {
            args.term = TerminateAfter::profilesec;
        }
        else
        {
            args.term = TerminateAfter::never;
        }

        if (args.term == TerminateAfter::never &&
            !(args.outputPath.empty()))
        {
            fprintf(stderr, "Warning: no output files will be written.\n");
        }

        return goodInputs;
    }

#pragma endregion "command line arguments"

#pragma region "file reading"

    // NOLINTBEGIN(concurrency-mt-unsafe)
    std::vector<std::filesystem::path> controlInput(const UserInputSettings *args)
    {
        const std::vector<std::string> *inputTasks = &args->inputPaths;
        const std::string filetype = ".mzML"; // @todo change this if other filetpes should be supported
        namespace fs = std::filesystem;
        std::vector<fs::path> outputTasks;
        const size_t inputLen = inputTasks->size();

        outputTasks.reserve(inputLen);
        struct TaskEntry
        {
            fs::path path;
            uintmax_t filesize = 0;
        };
        std::vector<TaskEntry> tasklist;
        tasklist.reserve(inputLen);
        // find all valid inputs and add them to the task list
        for (size_t path = 0; path < inputLen; path++)
        {
            const std::string *inputPath = inputTasks->data() + path;
            fs::path currentPath{*inputPath};
            if (!fs::exists(currentPath))
            {
                fprintf(stderr, "Warning: the file \"%s\" does not exist.\n", inputPath->c_str());
                continue;
            }
            currentPath = fs::canonical(currentPath);
            auto status = fs::status(currentPath);

            if (status.type() == fs::file_type::regular)
            {
                if (currentPath.extension() != filetype)
                {
                    fprintf(stderr, "Warning: only %s files are supported. The file \"%s\" has been skipped.\n",
                            filetype.c_str(), inputPath->c_str());
                    if (currentPath.extension() == ".mzml")
                    {
                        fprintf(stderr, "Warning: qAlgorithms file reading is case-sensitive."
                                        " Please change the file extension to \".mzML\"");
                    }
                    continue;
                }
                tasklist.push_back(TaskEntry{currentPath, fs::file_size(currentPath)});
            }
            else if (status.type() == fs::file_type::directory)
            {
                // recursively search for relevant files
                for (auto const &dir_entry : fs::recursive_directory_iterator(currentPath))
                {
                    fs::path recursivePath = fs::canonical(dir_entry);
                    if (recursivePath.extension() == filetype)
                    {
                        tasklist.push_back(TaskEntry{recursivePath, fs::file_size(recursivePath)});
                    }
                }
            }
            else
            {
                fprintf(stderr, "Warning: \"%s\" is not a supported file or directory."
                                " The file has been skipped.\n",
                        inputPath->c_str());
            }
        }
        // remove duplicate files
        size_t tasknumber = tasklist.size();
        unsigned int removedEntries = 0;
        if (tasknumber == 0)
        {
            fprintf(stderr, "Error: no valid files selected.\n");
            exit(1);
        }
        std::sort(tasklist.begin(), tasklist.end(),
                  [](const TaskEntry &lhs, const TaskEntry &rhs)
                  { return lhs.filesize < rhs.filesize; });
        size_t prevsize = tasklist[0].filesize;
        for (size_t i = 1; i < tasknumber; i++)
        {
            if (tasklist[i].filesize == prevsize)
            {
                const size_t readLength = 25000;
                std::ifstream fileConflict;
                char firstChars[readLength];
                char secondChars[readLength];
                fileConflict.open(tasklist[i - 1].path);
                fileConflict.read(firstChars, readLength);
                fileConflict.close();

                fileConflict.open(tasklist[i].path);
                fileConflict.read(secondChars, readLength);
                fileConflict.close();

                bool sameFiles = true;
                for (size_t j = 0; j < readLength; j++)
                {
                    if (firstChars[j] != secondChars[j])
                    {
                        sameFiles = false;
                        break;
                    }
                }
                if (sameFiles)
                {
                    tasklist[i - 1].filesize = 0; // always keeps last so comparison by file size works
                    ++removedEntries;
                }
            }
            prevsize = tasklist[i].filesize;
        }
        if (removedEntries > 0)
        {
            fprintf(stderr, "Warning: removed %u duplicate input files from processing queue.\n",
                    removedEntries);
        }
        for (size_t task = 0; task < tasklist.size(); task++)
        {
            TaskEntry *entry = tasklist.data() + task;
            if (entry->filesize > 0)
            {
                outputTasks.push_back(entry->path);
            }
        }

        const size_t skipAhead = args->skipAhead;
        if (tasklist.size() <= skipAhead)
        {
            fprintf(stderr, "Error: Value supplied to -skipAhead was %zu, but only %zu unique paths were supplied.\n",
                    skipAhead, tasklist.size());
            exit(1);
        }
        if (skipAhead != 0)
        {
            fprintf(stderr, "Warning: removing the first %zu elements from the tasklist.\n", skipAhead);
            if (skipAhead == 1)
            {
                outputTasks.erase(outputTasks.begin());
            }
            else
            {
                outputTasks.erase(outputTasks.begin(), outputTasks.begin() + skipAhead - 1);
            }
        }

        return (outputTasks);
    }
    // NOLINTEND(concurrency-mt-unsafe)

#pragma endregion "file reading"

#pragma region "print functions"
    // @todo use macros to move the boilerplate out of the function body

    static bool stopOverwrite(std::filesystem::path *pathOutput, bool noOverwrite)
    {
        if (std::filesystem::exists(*pathOutput))
        {
            if (noOverwrite)
            {
                const char format[] = "Warning: \"" _STR "\" already exists and will not be overwritten\n";
                fprintf(stderr, format, pathOutput->c_str());
                return true;
            }
            std::filesystem::remove(*pathOutput);
        }
        return false;
    }
    const char error_open_fail[] = "Error: could not open output path during centroid printing.\n"
                                   "No files have been written.Filename:\n" _STR "\n";

    void printProfileSections(XML_File *infile,
                              const UserInputSettings *inargs,
                              const std::vector<unsigned int> *selectedIndices,
                              std::string filename)
    {
        filename += "_profspec.csv";
        std::filesystem::path pathOutput = inargs->outputPath;
        pathOutput /= filename;
        if (stopOverwrite(&pathOutput, inargs->noOverwrite))
            return;

        std::vector<float> rt;
        infile->get_spectra_RT(selectedIndices, &rt);
        size_t startIdx = 0;
        size_t length = rt.size();
        clampSorted(rt.data(), &startIdx, &length,
                    inargs->prof_lim_rt_lower, inargs->prof_lim_rt_upper);

        // for all relevant retention times, print formatted output to a buffer. Buffer size should
        // be static, but solved via std::string here.
        std::vector<float> mz;
        float mz_min = INFINITY;
        float mz_max = 0;
        std::vector<float> intensity;

        FILE *outfile = fopen(pathOutput.c_str(), "w");
        if (outfile != nullptr)
        {
            fprintf(outfile, "idx_spec,rt,mz,intensity\n");
        }
        else
        {
            fprintf(stderr, "Error: fopen() failed, no data has been written\n");
            return;
        }

        size_t totalWritten = 0;
        for (size_t i = startIdx; i < length; i++)
        {
            unsigned int idx = selectedIndices->at(i);
            float rt_idx = rt.at(i);
            infile->get_spectrum(&mz, &intensity, idx);
            mz_min = (float)min(mz_min, mz[0]);
            mz_max = (float)max(mz_max, mz.back());
            size_t startSpec = 0;
            size_t lengthSpec = mz.size();
            clampSorted(mz.data(), &startSpec, &lengthSpec,
                        inargs->prof_lim_mz_lower, inargs->prof_lim_mz_upper);

            for (size_t point = 0; point < lengthSpec; point++)
            {
                size_t access = point + startSpec;
                totalWritten += fprintf(outfile, "%u,%f,%f,%f\n",
                                        idx, rt_idx, mz[access], intensity[access]);
            }
            mz.clear();
            intensity.clear();
        }

        fclose(outfile);

        if (!inargs->silent)
        {
            printf("File boundaries:\n    m/z: %f to %f\n    RT: %f to %f (min)\n",
                   mz_min, mz_max, rt[0] / 60, rt.back() / 60);
        }
        if (totalWritten == 0) // size of the header string is 25
        {
            fprintf(stderr, "Error: No regions with the specified properties:\n"
                            "mz range from %f to %f and RT range from %f to %f (min)\n"
                            "exist in the supplied data.\n",
                    inargs->prof_lim_mz_lower, inargs->prof_lim_mz_upper,
                    inargs->prof_lim_rt_lower / 60, inargs->prof_lim_rt_upper / 60);
            return;
        }

        if (!inargs->silent)
        {
            const char format[] = "writing profile section to: " _STR "\n";
            printf(format, pathOutput.c_str());
        }
    }

    void printCentroids(const std::vector<CentroidPeak> *peaktable,
                        std::vector<float> *convertRT,
                        std::filesystem::path pathOutput,
                        std::string filename,
                        bool silent, bool noOverwrite)
    {
        filename += "_centroids.csv";
        pathOutput /= filename;
        if (stopOverwrite(&pathOutput, noOverwrite))
            return;

        std::ofstream file_out;
        std::stringstream output;
        file_out.open(pathOutput, std::ios::out);
        if (!file_out.is_open())
        {

            fprintf(stderr, error_open_fail, pathOutput.c_str());
            return;
        }
        if (!silent)
        {
            const char format[] = "writing centroids to: " _STR "\n";
            printf(format, pathOutput.c_str());
        }
        output << "cenID,mz,mzUncertainty,number_MS1,retentionTime,area,areaUncertainty,"
               << "height,heightUncertainty,scale,DQSC,competitors\n";
        for (size_t j = 0; j < peaktable->size(); ++j)
        {
            const CentroidPeak peak = peaktable->at(j);
            char buffer[256];
            snprintf(buffer, 256, "%u,%0.6f,%0.6f,%u,%0.4f,%0.4f,%0.4f,%0.4f,%0.4f,%u,%0.5f,%u\n",
                     peak.ID, peak.mz, peak.mzUncertainty, peak.number_MS1, convertRT->at(peak.number_MS1),
                     peak.area, peak.areaUncertainty, peak.height, peak.heightUncertainty, peak.scale, peak.DQSC,
                     //  peak.interpolations,
                     peak.numCompetitors);
            output << buffer;
        }

        file_out << output.str();
        file_out.close();
    }

    void printBins(const std::vector<CentroidPeak> *centroids,
                   const std::vector<EIC> *bins,
                   //    const std::vector<float> *convertRT,
                   std::filesystem::path pathOutput,
                   std::string filename,
                   bool silent, bool noOverwrite)
    {
        filename += "_bins.csv";
        pathOutput /= filename;

        if (stopOverwrite(&pathOutput, noOverwrite))
            return;

        if (!silent)
        {
            const char format[] = "writing bins to: " _STR "\n";
            printf(format, pathOutput.c_str());
        }

        std::ofstream file_out;
        std::stringstream output;
        file_out.open(pathOutput, std::ios::out);
        if (!file_out.is_open())
        {
            fprintf(stderr, error_open_fail, pathOutput.c_str());
            return;
        }
        // @todo consider if the mz error is relevant when checking individual bins
        output << "binID,cenID,mz,mzUncertainty,retentionTime,number_MS1,area,height,degreesOfFreedom,DQSC\n";
        for (unsigned long binID = 0; binID < bins->size(); binID++)
        {
            const EIC *bin = bins->data() + binID;
            if (bin->scanNumbers.empty())
                continue;

            for (size_t i = 0; i < bin->mz.size(); i++)
            {
                const CentroidPeak cen = centroids->at(bin->cenID[i]);
                char buffer[128];
                snprintf(buffer, 128, "%lu,%u,%0.8f,%0.8f,%0.4f,%u,%0.6f,%0.6f,%u,%0.4f\n", // @todo re-add the dqsb once that works
                         binID, cen.ID, bin->mz[i], bin->predInterval[i],
                         bin->RT[i], bin->scanNumbers[i], bin->ints_area[i],
                         bin->ints_height[i], bin->df[i], bin->DQSC[i]);
                output << buffer;
            }
        }
        file_out << output.str();
        file_out.close();
    }

    void printFeatureList(const std::vector<FeaturePeak> *peaktable,
                          std::filesystem::path pathOutput,
                          std::string filename,
                          const std::vector<EIC> *originalBins,
                          const std::vector<float> *convertRT,
                          bool silent, bool noOverwrite)
    {
        filename += "_features.csv";
        pathOutput /= filename;

        if (stopOverwrite(&pathOutput, noOverwrite))
            return;

        if (!silent)
        {
            const char format[] = "writing features to: " _STR "\n";
            printf(format, pathOutput.c_str());
        }

        std::ofstream file_out;
        std::stringstream output;
        file_out.open(pathOutput, std::ios::out);
        if (!file_out.is_open())
        {
            fprintf(stderr, error_open_fail, pathOutput.c_str());
            return;
        }

        constexpr std::string_view header = "ID,binID,mz,mzUncertainty,retentionTime,RT_Uncertainty,"
                                            "lowestRetentionTime,highestRetentionTime,area,areaUncertainty,height,heightUncertainty,"
                                            "scale,DQSC,DQSB,DQSF,b0,b1,b2,b3\n";
        output << header;

        unsigned int ID = 1;
        for (size_t i = 0; i < peaktable->size(); i++)
        {
            const FeaturePeak peak = peaktable->at(i);
            unsigned long binID = peak.eic_ID;
            assert(binID < originalBins->size());
            float RT_start = 0;
            float RT_end = 0;

            char buffer[256];
            snprintf(buffer, 256, "%u,%lu,%0.6f,%0.6f,%0.4f,%0.4f,%0.4f,%0.4f,%0.3f,%0.3f,%0.3f,%0.3f,%lu,%0.5f,%0.5f,%0.5f,%0.8f,%0.8f,%0.8f,%0.8f\n",
                     ID, binID, peak.mz, peak.mzUncertainty,
                     peak.retentionTime, peak.RT_Uncertainty, RT_start, RT_end,
                     peak.area, peak.areaUncertainty, peak.height, peak.heightUncertainty, (unsigned long)peak.coefficients.scale,
                     peak.DQSC, peak.DQSB, peak.DQSF,
                     // properties relevant for componentisation, remove this later
                     peak.coefficients.b0, peak.coefficients.b1, peak.coefficients.b2, peak.coefficients.b3);
            output << buffer;
            ++ID;
        }

        file_out << output.str();
        file_out.close();
    }

#pragma endregion "print functions"
} // namespace qAlgorithms