// qalgorithms_ascii_logo.cpp

#include "../include/qalgorithms_ascii_logo.h"

namespace q
{
  namespace logo
  {
    void
    print_qpeaks()
    {
      HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
      int k = 0;

      SetConsoleTextAttribute(hConsole, 15);
      std::cout << " _______  _______  _______  _______  ___   _  _______ \n";
      std::cout << "|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQQQQQQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "PPPPPPP";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 10);
      std::cout << "EEEEEEE";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AAAAAAA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "KKK";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "| |";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "K";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 1);
      std::cout << "SSSSSSS";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|\n";

      std::cout << "|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQQQQQQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "PPPPPPP";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 10);
      std::cout << "EEEEEEE";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|_|";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "KKK";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|_|";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "K";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 1);
      std::cout << "SSSSSSS";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|\n";

      std::cout << "|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "| |";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "PPP";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|_|";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "P";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 10);
      std::cout << "EEE";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|___ |";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AAAAAAA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "KKKKKKK";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 1);
      std::cout << "S";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|_____ \n";

      std::cout << "|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|_|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "PPPPPPP";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 10);
      std::cout << "EEEEEEE";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AAAAAAA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "KKKKK";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|_ |";
      SetConsoleTextAttribute(hConsole, 1);
      std::cout << "SSSSSSS";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|\n";

      std::cout << "|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQQQQQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "| |";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "PPP";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|    |";
      SetConsoleTextAttribute(hConsole, 10);
      std::cout << "EEE";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|___ |";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AAAAAAA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "KKKKKKK";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "| _____|";
      SetConsoleTextAttribute(hConsole, 1);
      std::cout << "S";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|\n";

      std::cout << "|";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "QQQQ";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 12);
      std::cout << "Q";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 14);
      std::cout << "PPP";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|    |";
      SetConsoleTextAttribute(hConsole, 10);
      std::cout << "EEEEEEE";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "| |";
      SetConsoleTextAttribute(hConsole, 11);
      std::cout << "AA";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "KKK";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "| |";
      SetConsoleTextAttribute(hConsole, 13);
      std::cout << "K";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "||";
      SetConsoleTextAttribute(hConsole, 1);
      std::cout << "SSSSSSS";
      SetConsoleTextAttribute(hConsole, 15);
      std::cout << "|\n\n\n\n";
    }
  }
}
