---
title: "notebook for componentisation"
author: "Daniel Höhn"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r load ten stds, echo = FALSE}
SP01_f = read_csv("../../../master/SP_DDA_P1_positive_features.csv")
SP02_f = read_csv("../../../master/SP_DDA_P2_positive_features.csv")
SP03_f = read_csv("../../../master/SP_DDA_P3_positive_features.csv")
SP04_f = read_csv("../../../master/SP_DDA_P4_positive_features.csv")
SP05_f = read_csv("../../../master/SP_DDA_P5_positive_features.csv")
SP06_f = read_csv("../../../master/SP_DDA_P6_positive_features.csv")
SP07_f = read_csv("../../../master/SP_DDA_P7_positive_features.csv")
SP08_f = read_csv("../../../master/SP_DDA_P8_positive_features.csv")
SP09_f = read_csv("../../../master/SP_DDA_P9_positive_features.csv")
SP10_f = read_csv("../../../master/SP_DDA_P10_positive_features.csv")
```

```{r included standards}
M_H = 1.0078

standards <- data.frame(
  standard = c("Hydroxycotinine", "Hydroxycotinine-d3", "Anatabine", "Cotinine", 
               "Cotinine-d3", "Anabasine", "Anabasine-d4", "Vanillylmandelic acid", 
               "Homovanillic acid", "Atrazine desisopropyl", "Bisphenol A", 
               "Bisphenol A-d16", "3-phenoxybenzoic acid"),
  rt_expect = c(2.43, 2.45, 4.24, 5.39, 5.38, 5.61, 
                      5.61, 6.14, 7.67, 7.77, 11.69, 11.55, 13.55),
  mz = c(192.089877630, 195.108707868, 160.100048391, 176.094963011, 179.113793248, 
           162.115698455, 166.140805439, 198.05282342, 182.05790880, 173.0468230, 
           228.115029749, 244.215457684, 214.062994177),
  stringsAsFactors = FALSE
)
standards$mz = standards$mz + M_H
standards$rt_expect = standards$rt_expect * 60

candidates_rt = function(standards, SPP){
  # reduce the feature list to relevant RTs
  rts = standards$rt_expect
  retFrame = SP10_f[1,]
  for (rt in rts) {
    lower = SPP$retentionTime > rt - 30
    upper = SPP$retentionTime < rt + 30
    retFrame = rbind(retFrame, SPP[which(lower & upper),])
  }
  retFrame = retFrame[-1,]
  retFrame = retFrame[!duplicated(retFrame$ID), ]
  # same for mass
  retFrame2 = SP10_f[1,]
  for (mz in standards$mz) {
    tolerance = mz * 2 * 0.00001 # 20 ppm
    lower = retFrame$mz > mz - tolerance
    upper = retFrame$mz < mz + tolerance
    retFrame2 = rbind(retFrame2, retFrame[which(lower & upper),])
  }
  retFrame2 = retFrame2[-1,]
  retFrame2 = retFrame2[!duplicated(retFrame2$ID), ]
  return(retFrame2)
}

closestMass = function(standards, SPP){
  # return the standards dataframe with a feature ID added and the observed values for RT and mz
  standards$ID = 0
  standards$rt_observed = 0
  standards$mz_real = 0
  standards$area = 0
  standards$component = -1
  for (comp in 1:length(standards$mz)) {
    mz = standards$mz[comp]
    rt = standards$rt_expect[comp]
    # rt tolerance of 40 seconds
    rmv = !(SPP$retentionTime > rt - 30 & SPP$retentionTime < rt + 30)
    add = 10^100 * rmv
    lowestMZ = (SPP$mz - mz)^2 + add
    minPos = which(lowestMZ == min(lowestMZ))[1] # this is a bad error solution, rework for paper
    tolerance = mz * 2 * 0.00001 # 20 ppm
    
    standards$ID[comp] = SPP$ID[minPos]
    if(SPP$mz[minPos] > mz - tolerance & SPP$mz[minPos] < mz + tolerance){
      standards$rt_observed[comp] = SPP$retentionTime[minPos]
      standards$mz_real[comp] = SPP$mz[minPos]
      standards$component[comp] = SPP$CompID[minPos]
      standards$area[comp] = SPP$area[minPos]
    }
  }
  return(standards)
}
```

```{r}
proc_01 = closestMass(standards,candidates_rt(standards,SP01_f))
proc_01$repli = 1
proc_02 = closestMass(standards,candidates_rt(standards,SP02_f))
proc_02$repli = 2
proc_03 = closestMass(standards,candidates_rt(standards,SP03_f))
proc_03$repli = 3
proc_04 = closestMass(standards,candidates_rt(standards,SP04_f))
proc_04$repli = 4
proc_05 = closestMass(standards,candidates_rt(standards,SP05_f))
proc_05$repli = 5
proc_06 = closestMass(standards,candidates_rt(standards,SP06_f))
proc_06$repli = 6
proc_07 = closestMass(standards,candidates_rt(standards,SP07_f))
proc_07$repli = 7
proc_08 = closestMass(standards,candidates_rt(standards,SP08_f))
proc_08$repli = 8
proc_09 = closestMass(standards,candidates_rt(standards,SP09_f))
proc_09$repli = 9
proc_10 = closestMass(standards,candidates_rt(standards,SP10_f))
proc_10$repli = 10

total = rbind(proc_01, proc_02, proc_03, proc_04, proc_05, proc_06, proc_07, proc_08, proc_09, proc_10)
```

Only two of the found features are part of a component
```{r}
comp_anabasine_d4 = SP03_f[which(SP03_f$CompID == 91),]
comp_anabasine = SP10_f[which(SP10_f$CompID == 75),]
```

```{r effect intensity}
frame = rbind(SP01_f,SP02_f,SP03_f,SP04_f,SP05_f,SP06_f,SP07_f,SP08_f,SP09_f,SP10_f)
frame$comp = frame$CompID > 0
ggplot(frame)+
  geom_boxplot(aes(x = area, y = as.factor(comp)), outliers = FALSE)

ggplot(frame)+
  geom_boxplot(aes(x = log10(area), y = as.factor(comp)))

```
```{r}
total %>% group_by(standard) %>% summarise(repli = sum(component != -1))
total2 = total[which(total$component != -1),]
total2 %>% group_by(standard) %>% summarise(sd_mz = sd(mz_real), sd_rt = sd(rt_observed), area = mean(area))
```

